os:
  - windows
  - linux
  - osx
language: python
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install coveralls
  - pip install cairocffi>=1.0.0
  - pip install pytest-cov
  - pip install -r requirements.txt
  - python setup.py install
script:
#  - nosetests -v --with-coverage --cover-tests --cover-package tinyscript tests
  - pytest -v --cov=tinyscript --cov-append --cov-report="term-missing" tests
after_success:
  - coveralls
