language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python:
        - "3.8"
        - "3.7"
        - "3.6"
        - "pypy"
        - "pypy3"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
cache: pip
install:
  - pip install coveralls
  - pip install cairocffi>=1.0.0
  - pip install pytest-cov
  - pip install -r requirements.txt
  - python setup.py install
script:
#  - nosetests -v --with-coverage --cover-tests --cover-package tinyscript tests
  - pytest -v --cov=tinyscript --cov-append --cov-report="term-missing" tests
after_success:
  - coveralls
